---
name: Linter
on:
  pull_request:
    branches: [main]
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          FILTER_REGEX_INCLUDE: .*src/main/.*
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # mvnw is provided as is from the Maven Wrapper project. Can't change it
          FILTER_REGEX_EXCLUDE: .*mvnw